FIREBASE_URI = 'https://totem-db-38dee.firebaseio.com/'.freeze
RESOURCES_PATH = 'app/controllers/api/v1/resources/'.freeze
FIREBASE_PATH_KEY = RESOURCES_PATH + 'totem-db-38dee-firebase-adminsdk-8f9c4-6110e91b76.json'.freeze
FIREBASE_PROJECT_ID = 'totem-db-38dee'.freeze
FIREBASE_PRIVATE_KEY = File.open(FIREBASE_PATH_KEY).read.freeze
FIREBASE_API_KEY = 'AIzaSyCx2OEKeoSaSzx5h2YGjoahLEcZoTNqBaY'.freeze
FIREBASE_URL_V1_API = 'https://identitytoolkit.googleapis.com/v1/'.freeze

FIREBASE_USER_ACCOUNTS = (FIREBASE_URL_V1_API + 'accounts:').freeze
FIREBASE_TOKEN_SECURITY = (FIREBASE_URL_V1_API + 'token?key=').freeze


SIGN_UP_ACTION = 'signUp?key='.freeze
SIGN_IN_ACTION = 'signInWithPassword?key='.freeze
LOOK_UP_ACTION = 'lookup?key='.freeze
SEND_URL_ACTION = 'sendOobCode?key='.freeze
PWD_RESET_ACTION = 'resetPassword?key='.freeze
USER_UPDATE_ACTION = 'update?key='.freeze
DELETE_USER_ACTION = 'delete?key='.freeze

FIREBASE_SIGN_UP_USER = (FIREBASE_USER_ACCOUNTS + SIGN_UP_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_SING_IN_USER = (FIREBASE_USER_ACCOUNTS + SIGN_IN_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_CODE_PWD_RESET_USER = (FIREBASE_USER_ACCOUNTS + SEND_URL_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_PWD_RESET_USER = (FIREBASE_USER_ACCOUNTS + PWD_RESET_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_UPDATE_USER = (FIREBASE_USER_ACCOUNTS + USER_UPDATE_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_CHANGE_ID_USER = (FIREBASE_USER_ACCOUNTS + USER_UPDATE_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_REFRESH_TOKEN_USER = (FIREBASE_TOKEN_SECURITY + FIREBASE_API_KEY).freeze
FIREBASE_EMAIL_VALIDATION_USER = (FIREBASE_USER_ACCOUNTS + SEND_URL_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_EMAIL_CONFIRM_USER = (FIREBASE_USER_ACCOUNTS + USER_UPDATE_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_MANGE_INFO_USER = (FIREBASE_USER_ACCOUNTS + LOOK_UP_ACTION + FIREBASE_API_KEY).freeze
FIREBASE_DELETE_ACCOUNT_USER = (FIREBASE_USER_ACCOUNTS + DELETE_USER_ACTION + FIREBASE_API_KEY).freeze
